# 用来管理hellok8s pod
apiVersion: apps/v1
kind: Deployment # 表示资源类型
metadata:
  name: hellok8s-deployment # 名字需要是唯一的 
spec:
  # strategy:
  #   rollingUpdate: #滚动更新
  #     maxSurge: 1 # 峰值 可用=replicas+maxSurge
  #     maxUnavailable: 1 # 可用=replicas-maxUnavailable
  replicas: 3 # 部署的 pod 副本数量
  selector: # deployment 资源和 pod 资源关联的方式。这里表示 deployment 会管理（selector）所有 labels=hellok8s 的 pod。
    matchLabels:
      app: hellok8s
  template: # 用来定义 pod 资源的，你会发现和 Hellok8s Pod 资源的定义差不多，唯一的区别是需要加上 matadata.label 来和上面的 selector.matchLabels 对应起来
    metadata: # 不用matadata.name 是因为 deployment 会自动为我们创建 pod 唯一的 name。
      labels:
        app: hellok8s
    spec:
      containers:
        - image: zgj12306/hellok8s:v3
          name: hellok8s-container
          # livenessProbe: # 存活探针
          #   httpGet:
          #     path: /healthz
          #     port: 3000
          #   initialDelaySeconds: 3
          #   periodSeconds: 3

