# nginx 的 Pod
# kind 表示要创建的资源是 Pod 类型，metadata.name 表示要创建的 pod 的名字，是唯一的。spec.containers 表示要运行的容器名称和镜像名称。镜像默认来源 DockerHub。
# kubectl apply -f nginx.yaml 来创建nginx Pod。接着通过 kubectl get pods 来查看 pod 是否正常启动
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
    - name: nginx-container
      image: nginx